### ISSUE TITLE
Config AWS SDK to use bluebird

### ISSUE THREAD

**Issue by mccraveiro** [pagarme/sqs-quooler#3]
Instead of [wrapping](https://github.com/pagarme/sqs-quooler/blob/master/src/queue.ts#L60) the standard promise returned by the AWS SDK in a new bluebird Promise use `AWS.config.setPromisesDependency` to set bluebird as the default Promise lib. 

http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/using-promises.html#w1ab1c17c19c17c21

**Comment by mccraveiro** [comment]
@grvcoelho what's your opinion on this?
You said before that you prefer wrapping over configuration. 
Should we close this issue?

**Comment by otaviopace** [comment]
This is a cool feature in my opinion!
